### ISSUE TITLE
Cannot click repository in VS Code

### ISSUE THREAD

**Issue by Gilwyad** [martinwepner/PascalCase-camelCase-to-snake_case#2] opened 2020-01-16 14:25 UTC
Clicking the 'repository' button in VS Code results in the following error, instead of opening this GitHub repo:

> Unable to open 'PascalCase-camelCase-to-snake_case.git': resource is not available.

**Comment by martinwepner** [comment] 2022-02-22 13:17
Thank you for reporting this issue. Unfortunately I cannot reproduce this so I would close it for now.

**Closed as completed by martinwepner** 2022-02-22 13:17 UTC
